[project]
name = "psiexperiment"
description = "Framework for running trial-based experiments"
readme = "readme.md"
requires-python = ">=3.7"
license = {file = "LICENSE.txt"}
authors = [
    {name = "Brad Buran", email="bburan@alum.mit.edu"},
    {name = "Brad Buran", email="buran@ohsu.edu"},
    {name = "Buran Consulting, LLC", email="info@bradburan.com"}
]
maintainers = [
    {name = "Brad Buran", email="bburan@alum.mit.edu"},
    {name = "Brad Buran", email="buran@ohsu.edu"},
    {name = "Buran Consulting, LLC", email="info@bradburan.com"}
]
dependencies = [
    "psidata",
    "psiaudio",
    "enaml[qt5-pyqt] >=0.13.0",
    "numpy",
    "palettable",
    "pyqtgraph >=0.11.0",
    "scipy",
    "pandas",
    "pyyaml",
]
dynamic = ["version"]

[project.optional-dependencies]
ni = ["pydaqmx"]
tdt = ["tdtpy >=0.9.0"]
docs = ["sphinx", "sphinx_rtd_theme", "pygments-enaml"]
tqdm = ["tqdm"]                                           # Used in post-processing from command line.
test = ["pytest", "pytest-console-scripts", "matplotlib"] # Matplotlib is used in some of the validation scripts.
bcolz-backend = ["bcolz"]						  		  # No public build exists for Python 3.7+. You will have to make this yourself.
zarr-backend = ["zarr"]
dev = ["coloredlogs"]

[project.scripts]
psi = "psi.application.psi_launcher:main"
psi-config = "psi.application:config"

[build-system]
requires = ["setuptools>=61.2", "wheel", "setuptools_scm[toml]>=3.4.3"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "psi/version.py"
