name: Publish Python distribution to PyPI
on: 
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
  pypi-publish:
    name: Build and publish Python distribution to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ncrar-dkm-tools
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@main
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install pypa/build
        run: >-
          python -m 
          pip install 
          build 
          --user
      - name: Build a binary wheel and a source tarball
        run: >-
          python -m 
          build 
          --sdist
          --wheel
          --outdir dist/
      - name: Publish distribution to PyPI
        if: startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
